remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

title: Junkyard Genius
description: 338 insane DIY builds from salvaged appliances, e-waste, chemicals, and junk.
url: https://rbrents3000.github.io
baseurl: /junkyard-genius

social:
  name: Junkyard Genius
  links:
    - "https://github.com/rbrents3000/junkyard-genius"

defaults:
  - scope:
      path: ""
    values:
      image: /images/og-social.jpg
